### ISSUE TITLE
Print icon is hard coded?

### ISSUE THREAD

**Issue by coomsie** [CanterburyRegionalCouncil/wab-widgets#11]
Icon which shows the pdf icon ...

![image](https://user-images.githubusercontent.com/125121/28802955-5c37d8b8-76ad-11e7-869b-a1fb46b63e1e.png)

``<img src="./widgets/PrintPlus/images/pdf.png">``

**Comment by cbs-greg** [comment]
@cristiangimenez86 - please can you take a look at this?

**Comment by cristiangimenez86** [comment]
Hi,

The pdf icon url is in "PrintPlus.js"
pdfIcon: require.toUrl("./widgets/PrintPlus/images/pdf.png"),

![image](https://user-images.githubusercontent.com/5216487/28952743-4cc26fde-7927-11e7-9ea9-9fd27ff3a3e4.png)

Cheers.
Cristian

**Comment by coomsie** [comment]
correct it is hard coded to the widget name 

./widgets/PrintPlus/image

the reference should be relative to the widget

the name can change.

**Comment by cristiangimenez86** [comment]
Since we are using require to get the image, I can't use relative paths like ..\..\ 

Please see: https://github.com/requirejs/requirejs/issues/550

The solution suggested in the answer is to create a new module Id in requirejs.config but unfortunately the configurations are handled globally (I think) because I couldn't find any requirejs.config within PrintPlus widget folder.

The easy way to do this fix is to have a new key in our config.json (the same file to config the layouts, scales, etc) with the name of the widget so we can have something like: 

![image](https://user-images.githubusercontent.com/5216487/28954963-dc0da8d4-7936-11e7-984e-5d24aba112c9.png)

![image](https://user-images.githubusercontent.com/5216487/28954916-8b9a760c-7936-11e7-8a9c-a9d91891ffcc.png)

What do you think?

**Comment by coomsie** [comment]
path is coming out as undefined ....

<img src="./widgets/undefined/images/pdf.png">

**Comment by cristiangimenez86** [comment]
I think is because there is a config outside of the widgets folder that must be set. I have no idea why PrintPlus widget creates this external config by default but it seems like is using that config and not the internal one. Could you check if that config has the property widgetName?

![image](https://user-images.githubusercontent.com/5216487/29199851-6d84bbb4-7ea4-11e7-8bec-a882f557ab90.png)

**Comment by coomsie** [comment]
Yeah both config's are up to date ... so that is not the issue.

the config folder is the instance of the widget .. the config in the widget directory is the class config ... if there is no instance set then it get it from the widget folder....

this then allows multi configs per instance, than restricting it to one config regardless...
